site_name: Struktur Data & Algoritma
site_description: Dokumentasi Struktur Data & Algoritma
site_author: Delvin De Vito
theme:
  name: material
  copyright: 'Dokumentasi ini dibuat oleh [Nama Anda]'
extra_css:
  - assets/stylesheets/navigation.css
nav:
  - Home: index.md
  - Struktur Data:
      - Overview: struktur-data/index.md
      - LinkedList:
          - Overview: struktur-data/linkedlist/index.md
          - Implementasi: struktur-data/linkedlist/implementasi.md
          - Aplikasi: struktur-data/linkedlist/aplikasi.md
      - Stack:
          - Overview: struktur-data/stack/index.md
          - Implementasi: struktur-data/stack/implementasi.md
          - Aplikasi: struktur-data/stack/aplikasi.md
      - BST:
          - Overview: struktur-data/bst/index.md
          - Implementasi: struktur-data/bst/implementasi.md
          - Aplikasi: struktur-data/bst/aplikasi.md
  - Algoritma: algoritma/index.md
  - Pemrograman: pemrograman/index.md
